<?= $this->fetch('header.phtml') ?>



    <div class="card">
        <div class="card-body">
            <div class="card-text">
                <ul class="list-group">
                    <?php foreach ($users as $user): ?>

                        <li class="list-group-item large">
                            <?= htmlspecialchars($user['userName'], ENT_QUOTES, 'UTF-8', false) ?><br>


<!--                            <a href="/board/--><?//= e($user['id']) ?><!--/edit" class="btn btn-primary right">編集</a>-->
<!--                            <button class="btn btn-danger right" data-toggle="modal" data-target="#deleteModal--><?//= $user['id'] ?><!--">削除</button></li>-->


                        <!-- modal-->
<!--                        <div class="modal fade" id="deleteModal--><?//= $user['id'] ?><!--" tabindex="-1" role="dialog">-->
<!--                            <div class="modal-dialog" role="document">-->
<!--                                <div class="modal-content">-->
<!--                                    <div class="modal-header">-->
<!--                                        <h5 class="modal-title">投稿の削除</h5>-->
<!--                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">-->
<!--                                            <span aria-hidden="true">&times;</span>-->
<!--                                        </button>-->
<!--                                    </div>-->
<!--                                    <div class="modal-body">-->
<!--                                        <p>本当に削除してよろしいですか？</p>-->
<!--                                    </div>-->
<!--                                    <form method="post" action="/board/--><?//= $user['id'] ?><!--" id="modal-delete--><?//=$user['id'] ?><!--">-->
<!--                                        <input type="hidden" name="_METHOD" value="delete">-->
<!---->
<!--                                        <button type="submit"  form="modal-delete--><?//=$user['id'] ?><!--" class="btn btn-danger right">削除</button>-->
<!--                                        <button type="button" class="btn btn-secondary right" data-dismiss="modal">キャンセル</button>-->
<!--                                        -->
<!--                                    </form>-->
<!--                                </div>-->
<!--                                -->
<!--                            </div>-->
<!--                        </div>-->

                    <?php endforeach; ?>
                </ul>

            </div>
        </div>
    </div>
    <a href="/logout">logout</a>


<?= $this->fetch('footer.phtml') ?>