<?= $this->fetch('header.phtml') ?>



    <div class="row">
        <div class="col s12">
            <div class="card">
                <div class="card-content">
                    <span class="card-title center">簡易掲示板</span>

                    <p>会員登録すれば、読めるし、書き込めるよ。なんでも書き込んでね！</p>

                </div>
                <div class="card-action">
                    <a class="btn" href="/register">新規登録</a>
                    <a class="btn right" href="/login">ログイン</a>
                </div>
            </div>
        </div>
    </div>





<p class="#00bfa5 teal accent-4">実装機能</p>

<ul>
    <li>ログイン</li>
    <li>ログインチェック</li>
    <li>mypage</li>
    <li>投稿、編集、削除</li>

</ul>




<p class="#00bfa5 teal accent-4">頑張ったところ</p>

    <ul>
        <li>routing(mypageなどというものを作ってしまいページ数が増え、なんども見直した)</li>
        <li>relationDB（繋ぐのむずかった）</li>
        <li>modal（ワンクッションのはずが...）</li>
        <li>materializeのjs(結局動かない)</li>
    </ul>

    <p class="#00bfa5 teal accent-4">やりたかったこと（今月末までには...）</p>

    <ul>
        <li>見栄えを気にする（せっかくmaterialize使ってるのに...）</li>
        <li>バリデーション（途中）</li>
        <li>エラーを返す</li>
        <li>投稿数のグラフ化</li>
        <li>いいね</li>
    </ul>







<?$this->fetch('footer.phtml') ?>