<?= $this->fetch('header.phtml') ?>





<div class="row">
    <div class="col s12">
        <div class="card ">
            <div class="card-content">
                <span class="card-title">New Comment</span>


                    <form method="POST" class="col s12" action="/newComment/<?= $_SESSION['user']['userName'];var_dump($_SESSION['user']['userName']); ?>">
                        <div class="row">
                            <div class="input-field col s12">
                                <textarea id="textarea1" class="materialize-textarea" data-length="120"></textarea>
                                <label for="textarea1">Textarea</label>
                            </div>
                        </div>
                        <input type="submit" class="btn right">
                    </form>



            </div>
        </div>
    </div>
</div>

























<?$this->fetch('footer.phtml') ?>
