<?= $this->fetch('header.phtml') ?>



<div class="card">

    <div class="card-content">
        <span class="card-title center">新規登録</span>

        <div class="row">
            <form method="POST" action="/register" class="col s12">
                <div class="row">
                    <div class="input-field col s12">
                        <input type="text" name="userName" id="userName" class="validate">
                        <label for="userName">ユーザー名</label>
                    </div>
                </div>

                <div class="row">
                    <div class="input-field col s12">
                        <input type="text" name="password" id="password" class="validate">
                        <label for="password">password</label>
                    </div>
                </div>

                <div class="row">
                    <div class="input-field col s12">
                        <input id="email" type="email" name="email" class="validate">
                        <label for="email">Email</label>
                    </div>
                </div>

                <button class="btn btn-primary right">送信</button>
            </form>
        </div>

    </div>

</div>
    <a href="/">TOPに戻る</a>




<?= $this->fetch('footer.phtml') ?>