<?= $this->fetch('header.phtml') ?>



    <div class="card">
        <div class="card-body">
            <div class="card-text">
                <ul class="list-group">
                    <?php foreach ($users as $user): ?>

                        <li class="list-group-item large">
                            <?= htmlspecialchars($user['userName'], ENT_QUOTES, 'UTF-8', false) ?><br>
                            <?= htmlspecialchars($user['comment'], ENT_QUOTES, 'UTF-8', false) ?><br>
                        </li>

                    <?php endforeach; ?>
                </ul>
                <a href="/myPage">my page</a>
            </div>
        </div>
    </div>
    <a href="/logout">logout</a>


<?= $this->fetch('footer.phtml') ?>